services:
  db:
    image: "mongo:latest"
    container_name: spoo_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongouser
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: "redis:latest" # reccommended by offical docs
    container_name: spoo_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spoo_app
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --no-access-log --reload
    volumes:
      # This mount enables hot reloading for your application code
      - .:/app
      # This mount masks the host's .venv from overwriting the container's .venv
      - /app/.venv
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env
    environment:
      - MONGODB_URI=mongodb://mongouser:mongouser@db:27017
      - REDIS_URI=redis://redis:6379/0

volumes:
  mongo-data:
  mongo-config:
