"""
FastAPI dependency providers.

Re-exports all dependencies from sub-modules for convenient
``from dependencies import X`` imports.
"""

from dependencies.auth import (
    SHORTEN_SCOPES,
    STATS_SCOPES,
    URL_MANAGEMENT_SCOPES,
    URL_READ_SCOPES,
    AuthUser,
    CurrentUser,
    JwtUser,
    JwtVerifiedUser,
    OptionalUser,
    VerifiedUser,
    check_api_key_scope,
    get_current_user,
    optional_scopes,
    optional_scopes_verified,
    require_auth,
    require_jwt,
    require_jwt_verified,
    require_scopes,
    require_verified_email,
)
from dependencies.infra import (
    AppRegistryDep,
    JwtConfig,
    OAuthProviders,
    Settings,
    get_app_registry,
    get_db,
    get_email_provider,
    get_geoip_service,
    get_jwt_config,
    get_oauth_providers,
    get_redis,
    get_settings,
)
from dependencies.services import (
    ApiKeySvc,
    AppGrantRepo,
    ClickSvc,
    ContactSvc,
    CredentialSvc,
    DeviceAuthSvc,
    ExportSvc,
    OAuthSvc,
    PasswordSvc,
    ProfilePictureSvc,
    StatsSvc,
    UrlSvc,
    UserRepo,
    VerificationSvc,
    fetch_user_profile,
    get_api_key_service,
    get_app_grant_repo,
    get_click_service,
    get_contact_service,
    get_credential_service,
    get_device_auth_service,
    get_export_service,
    get_oauth_service,
    get_password_service,
    get_profile_picture_service,
    get_stats_service,
    get_url_service,
    get_user_repo,
    get_verification_service,
)

__all__ = [
    "SHORTEN_SCOPES",
    "STATS_SCOPES",
    "URL_MANAGEMENT_SCOPES",
    "URL_READ_SCOPES",
    # services (aliases)
    "ApiKeySvc",
    "AppGrantRepo",
    # infra
    "AppRegistryDep",
    # auth
    "AuthUser",
    "ClickSvc",
    "ContactSvc",
    "CredentialSvc",
    "CurrentUser",
    "DeviceAuthSvc",
    "ExportSvc",
    "JwtConfig",
    "JwtUser",
    "JwtVerifiedUser",
    "OAuthProviders",
    "OAuthSvc",
    "OptionalUser",
    "PasswordSvc",
    "ProfilePictureSvc",
    "Settings",
    "StatsSvc",
    "UrlSvc",
    "UserRepo",
    "VerificationSvc",
    "VerifiedUser",
    "check_api_key_scope",
    # services (getters)
    "fetch_user_profile",
    "get_api_key_service",
    "get_app_grant_repo",
    "get_app_registry",
    "get_click_service",
    "get_contact_service",
    "get_credential_service",
    "get_current_user",
    "get_db",
    "get_device_auth_service",
    "get_email_provider",
    "get_export_service",
    "get_geoip_service",
    "get_jwt_config",
    "get_oauth_providers",
    "get_oauth_service",
    "get_password_service",
    "get_profile_picture_service",
    "get_redis",
    "get_settings",
    "get_stats_service",
    "get_url_service",
    "get_user_repo",
    "get_verification_service",
    "optional_scopes",
    "optional_scopes_verified",
    "require_auth",
    "require_jwt",
    "require_jwt_verified",
    "require_scopes",
    "require_verified_email",
]
